In [2]:
import torch

In [2]:
t = torch.Tensor([1,2,3])

In [3]:
t

tensor([1., 2., 3.])

In [4]:
import numpy as np

In [5]:
a = np.array([1,2,3])

In [6]:
torch.Tensor(a)

tensor([1., 2., 3.])

In [7]:
import pandas as pd

In [8]:
df = pd.DataFrame(a)

In [9]:
df

,0
0,1
1,2
2,3


In [11]:
torch.tensor(df.to_numpy())

tensor([[1],
        [2],
        [3]])

In [13]:
df.to_numpy().shape

(3, 1)

In [14]:
a.shape

(3,)

In [15]:
t2 = torch.zeros((2,3,4))

In [16]:
t2

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [18]:
t3 = t2.long()

In [19]:
t3

tensor([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]])

In [1]:
from ucimlrepo import fetch_ucirepo 
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
from random import choices, sample

In [2]:
iris = fetch_ucirepo(id=53) 

In [3]:
scaler = MinMaxScaler((-1, 1))

In [4]:
import pickle
with open("iris.pkl", "wb") as irisfile:
    pickle.dump(iris, irisfile)

In [5]:
X = iris.data.features 
y = iris.data.targets 

In [14]:
classes = list(set(iris.data.targets['class']))

In [39]:

y = iris.data.targets.apply(lambda x: classes.index(x['class']), axis=1)

In [27]:
import numpy as np

In [40]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Length: 150, dtype: int64

In [41]:
list(zip([x.to_numpy() for x in list(zip(*X.iterrows()))[1]], list(y)))

[(array([5.1, 3.5, 1.4, 0.2]), 0),
 (array([4.9, 3. , 1.4, 0.2]), 0),
 (array([4.7, 3.2, 1.3, 0.2]), 0),
 (array([4.6, 3.1, 1.5, 0.2]), 0),
 (array([5. , 3.6, 1.4, 0.2]), 0),
 (array([5.4, 3.9, 1.7, 0.4]), 0),
 (array([4.6, 3.4, 1.4, 0.3]), 0),
 (array([5. , 3.4, 1.5, 0.2]), 0),
 (array([4.4, 2.9, 1.4, 0.2]), 0),
 (array([4.9, 3.1, 1.5, 0.1]), 0),
 (array([5.4, 3.7, 1.5, 0.2]), 0),
 (array([4.8, 3.4, 1.6, 0.2]), 0),
 (array([4.8, 3. , 1.4, 0.1]), 0),
 (array([4.3, 3. , 1.1, 0.1]), 0),
 (array([5.8, 4. , 1.2, 0.2]), 0),
 (array([5.7, 4.4, 1.5, 0.4]), 0),
 (array([5.4, 3.9, 1.3, 0.4]), 0),
 (array([5.1, 3.5, 1.4, 0.3]), 0),
 (array([5.7, 3.8, 1.7, 0.3]), 0),
 (array([5.1, 3.8, 1.5, 0.3]), 0),
 (array([5.4, 3.4, 1.7, 0.2]), 0),
 (array([5.1, 3.7, 1.5, 0.4]), 0),
 (array([4.6, 3.6, 1. , 0.2]), 0),
 (array([5.1, 3.3, 1.7, 0.5]), 0),
 (array([4.8, 3.4, 1.9, 0.2]), 0),
 (array([5. , 3. , 1.6, 0.2]), 0),
 (array([5. , 3.4, 1.6, 0.4]), 0),
 (array([5.2, 3.5, 1.5, 0.2]), 0),
 (array([5.2, 3.4, 1

In [25]:
scaler.fit(X)

MinMaxScaler(feature_range=(-1, 1))

In [26]:
X_scaled = scaler.transform(X)

In [27]:
X_scaled = pd.DataFrame(X_scaled, index=X.index, columns=X.columns)

In [ ]:
class IrisModel(nn.Module):
    def __init__(self):
        super(IrisModel, self).__init__()
        self.layer0 = nn.Linear(4, 3)
        self.logsoftmax = nn.LogSoftmax()

    def forward(self, i):
        output = self.layer0(i)
        output = self.logsoftmax(output)
        return output

In [1]:
import torcheval

In [3]:
T = [torch.Tensor(3), torch.Tensor(3), torch.Tensor(3)]

In [4]:
T

[tensor([-7.6975e-27,  4.5904e-41,  5.1560e-33]),
 tensor([1.4604e-03, 4.5905e-41, 1.4604e-03]),
 tensor([5.2746e-12, 4.5905e-41, 7.1887e-43])]

In [7]:
torch.stack(T)

tensor([[-7.6975e-27,  4.5904e-41,  5.1560e-33],
        [ 1.4604e-03,  4.5905e-41,  1.4604e-03],
        [ 5.2746e-12,  4.5905e-41,  7.1887e-43]])