In [1]:
import torch

In [2]:
t = torch.Tensor([1,2,3])

In [3]:
t

tensor([1., 2., 3.])

In [4]:
import numpy as np

In [5]:
a = np.array([1,2,3])

In [6]:
torch.Tensor(a)

tensor([1., 2., 3.])

In [7]:
import pandas as pd

In [8]:
df = pd.DataFrame(a)

In [9]:
df

,0
0,1
1,2
2,3


In [11]:
torch.tensor(df.to_numpy())

tensor([[1],
        [2],
        [3]])

In [13]:
df.to_numpy().shape

(3, 1)

In [14]:
a.shape

(3,)

In [15]:
t2 = torch.zeros((2,3,4))

In [16]:
t2

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [18]:
t3 = t2.long()

In [19]:
t3

tensor([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]])

In [20]:
from ucimlrepo import fetch_ucirepo 
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
from random import choices, sample

In [21]:
iris = fetch_ucirepo(id=53) 

In [22]:
scaler = MinMaxScaler((-1, 1))

In [24]:
X = iris.data.features 
y = iris.data.targets 

In [25]:
scaler.fit(X)

MinMaxScaler(feature_range=(-1, 1))

In [26]:
X_scaled = scaler.transform(X)

In [27]:
X_scaled = pd.DataFrame(X_scaled, index=X.index, columns=X.columns)

In [ ]:
class IrisModel(nn.Module):
    def __init__(self):
        super(IrisModel, self).__init__()
        self.layer0 = nn.Linear(4, 3)
        self.logsoftmax = nn.LogSoftmax()

    def forward(self, i):
        output = self.layer0(i)
        output = self.logsoftmax(output)
        return output